version: "3.7"
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    networks:
      - default
    ports:
      - 80:80
      # - 443:443
      - 808  0:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - ./config/traefik-router.yml:/etc/traefik/config/traefik-router.yml

# 指定網路
networks:
  default:
    external: true
    name: reverse-proxy
