http:
  routers:
    librenms-router:
      rule: "Host(`monitor.com`)"
      service: librenms-service

  services:
    librenms-service:
      loadBalancer:
        servers:
          - url: "http://librenms-container:8081"
