version: "3.7"

services:
  # prometheus 設定
  prometheus:
    container_name: prome
    image: prom/prometheus:latest
    volumes:
      - './config/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.monitor.com`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.monitor.com`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  default:
    external: true
    name: reverse-proxy