version: "3.7"

services:
  # prometheus 設定
  prometheus:
    container_name: prome
    image: prom/prometheus:latest
    volumes:
      - './config/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librenms.rule=Host(`prometheus.monitor.com`)"
      - "traefik.http.routers.librenms.entrypoints=web"
      - "traefik.http.services.librenms.loadbalancer.server.port=80"


  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librenms.rule=Host(`grafana.monitor.com`)"
      - "traefik.http.routers.librenms.entrypoints=web"
      - "traefik.http.services.librenms.loadbalancer.server.port=80"
networks:
  default:
    external: true
    name: reverse-proxy