version: "3.7"

services:
  # prometheus 設定
  prometheus:
    container_name: prome
    image: prom/prometheus:latest
    volumes:
      - './config/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000