version: "3.7"

services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./librenms_data/logs:/opt/librenms/logs
      - ./librenms_data/rrd:/opt/librenms/rrd
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=LibreNMS_DB
      - TZ=Asia/Taipei
    restart: always

  librenms:
    image: jarischaefer/docker-librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./librenms_data/mysql:/var/lib/mysql
    ports:
      - 8081:80 #80 port 被traefik佔住
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      APP_KEY: BaxvYlEofWi7glfTQ6cAfh5Ws137QGlYSujob56TF+I=
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_NAME: LibreNMS_DB
      DB_USER: LibreNMS
      DB_PASS: p@ssw0rd
      TZ: Asia/Taipei
      POLLER: 24
      SERVICES_ENABLED: 1
      UPDATE_CHANNEL: master
      SYSLOG_ENABLED: 1
      BASE_URL: http://librenms.monitor.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librenms.rule=Host(`librenms.monitor.com`)"
      - "traefik.http.routers.librenms.entrypoints=web"
      - "traefik.http.services.librenms.loadbalancer.server.port=80"

networks:
  default:
    external:
      name: reverse-proxy
