version: "3.7"

services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - MYSQL_DATABASE=libreNMS
      - TZ=Asia/Taipei
    restart: always

  librenms:
    image: jarischaefer/docker-librenms
    container_name: librenms_2
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 8081:80
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      APP_KEY: base64:DVRiovLGAyZfuxj+Zw/3Mc89cJv4xc55/R98AbVHUKo=
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_NAME: libreNMS
      DB_USER: root
      DB_PASS: p@ssw0rd
      TZ: Asia/Taipei
      POLLER: 24
      SERVICES_ENABLED: 1
      UPDATE_CHANNEL: master
      SYSLOG_ENABLED: 1
      BASE_URL: http://192.168.139.137:8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librenms.rule=Host(`librenms.monitor.com`)"
      - "traefik.http.routers.librenms.entrypoints=web"
      - "traefik.http.services.librenms.loadbalancer.server.port=80"
    restart: always
networks:
  default:
    external: true
    name: reverse-proxy
