version: '3.7'
services:
  pushgateway:
    image: prom/pushgateway
    volumes:
    - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    - ./prometheus_data:/prometheus
    ports:
      - "9091:9091"