name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20'
      CHECK_REPO_URL: https://hub.docker.com/v2/repositories/monitor
      DOCKER_CONFIG: ${{ secrets.DOCKERHUB_CONFIG }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Check if Docker Hub repository exists
      id: check_repo
      run: |
        status_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.CHECK_REPO_URL }})
        if [[ "$status_code" -ne 404 ]]; then
          echo "REPO_EXISTS=true" >> $GITHUB_ENV
        fi
      continue-on-error: true 

    - name: Build and Push Docker Images
      run: |
        for service_folder in */; do
          service_name=$(basename $service_folder)
          echo "Building and pushing Docker image for service: $service_name"