name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Check if Docker Hub repository exists
      run: |
        echo "Checking if Docker Hub repository exists..."
        curl -s -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/linda1110929/monitor
      continue-on-error: true # 忽略失败，以允许后续步骤继续执行

    - name: Build and Push Docker Images
      run: |
        for service_folder in */; do
          service_name=$(basename $service_folder)
          echo "Building and pushing Docker image for service: $service_name"
          cd $service_folder
          docker-compose build
          docker-compose push
          cd ..
        done
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
